name: thunderbird
version: "91.7.0"
summary: Mozilla Thunderbird email application
description: Thunderbird is a free email application that’s easy to set up and customize - and it’s loaded with great features!
confinement: strict
grade: stable
base: core20
compression: lzo

apps:
  thunderbird:
    command-chain: [ bin/gpg-shim, bin/tmpdir ]
    command: thunderbird-bin
    extensions: [ gnome-3-38 ]
    environment:
      DISABLE_WAYLAND: 1
      HOME: "$SNAP_USER_COMMON"
      GTK_USE_PORTAL: 1
    plugs:
      - avahi-observe
      - browser-sandbox
      - camera
      - cups-control
      - gsettings
      - gpg-keys
      - home
      - network
      - network-control
      - opengl
      - audio-playback
      - removable-media
      - u2f-devices

plugs:
  browser-sandbox:
    interface: browser-support
    allow-sandbox: true
  etc-thunderbird-policies:
    interface: system-files
    read: [/etc/thunderbird/policies]

parts:
  thunderbird:
    plugin: dump
    source: https://archive.mozilla.org/pub/thunderbird/releases/$SNAPCRAFT_PROJECT_VERSION/linux-x86_64/en-US/thunderbird-$SNAPCRAFT_PROJECT_VERSION.tar.bz2
    build-packages:
      - curl
    stage-packages:
      - desktop-file-utils
      - gnupg # Needed to use Thunderbird >78 with smartcards.
      - gnupg-agent # Needed to use Thunderbird >78 with smartcards.
      - libblkid1
      - libgcrypt20
      - libgpg-error0
      - libgpgme11 # Needed to use Thunderbird >78 with smartcards.
      - liblzma5
      - libudev1
      - libuuid1
      - zlib1g
      - liblz4-1
      - libxt6
    organize:
      "snap/thunderbird/current/usr/*": usr/lib/thunderbird
    override-build: |
      snapcraftctl build
      set -eux
      cp -pr $SNAPCRAFT_PROJECT_DIR/distribution $SNAPCRAFT_PART_INSTALL
      mkdir $SNAPCRAFT_PART_INSTALL/distribution/extensions
      for locale in de es-ES fr it ja pt-PT pt-BR ru zh-CN; do curl -o "$SNAPCRAFT_PART_INSTALL/distribution/extensions/langpack-$locale@thunderbird.mozilla.org.xpi" "https://releases.mozilla.org/pub/thunderbird/releases/$SNAPCRAFT_PROJECT_VERSION/linux-x86_64/xpi/$locale.xpi"; done
      mkdir -p $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PROJECT_DIR/gpg-shim $SNAPCRAFT_PART_INSTALL/bin/
      cp -p $SNAPCRAFT_PROJECT_DIR/tmpdir $SNAPCRAFT_PART_INSTALL/bin/
    prime: 
      - -usr/lib/*/libgio*
      - -usr/lib/*/libglib*
      - -usr/lib/*/libgm*

  # Find files provided by the base and platform snap and ensure they aren't
  # duplicated in this snap
  cleanup:
    after: [thunderbird]
    plugin: nil
    build-snaps: [core20, gnome-3-38-2004]
    override-prime: |
      set -eux
      for snap in "core20" "gnome-3-38-2004"; do
        cd "/snap/$snap/current" && find . -type f,l -exec rm -f "$SNAPCRAFT_PRIME/{}" \;
      done

